[package]
name = "april"
version = "0.1.0"
authors = ["Mitchell Bruckner <mbruckner807@gmail.com>"]
build = "build.rs"


[dependencies]
image = { version = "0.18", optional = true }

[build-dependencies]
bindgen = "0.26.3"
cc = "1.0"

[features]
default = ["image"]

